apiVersion: apps/v1
kind: Deployment
metadata:
  name: klog
  namespace: klog
spec:
  selector:
    matchLabels:
      app: klog
  template:
    metadata:
      labels:
        app: klog
    spec:
      containers:
      - name: klog
        image: kleverio/klog:sample
        imagePullPolicy: Always
        env:
          - name: LOG_LEVEL
            value: debug
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: klog
  namespace: klog
spec:
  selector:
    app: klog
  ports:
  - port: 50051
    targetPort: 50051