on:
  workflow_call:
    inputs:
      extra_label:
        required: false
        default: klever-pipe
        type: string
      go_private:
        required: false
        type: string
      flavor:
        required: false
        type: string
        default: golang
      registry_name:
        required: false
        type: string
        default: gettyio
    secrets:
      registry_user:
        required: true
      registry_pass:
        required: true
      git_user:
        required: false
      git_pass:
        required: false
jobs:
  setup:
    env:
      USER: ${{ secrets.git_user }}
      TOKEN: ${{ secrets.git_pass }}
      GO_PRIVATE: ${{ inputs.go_private }}

    runs-on: ["self-hosted", "${{ inputs.extra_label }}"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Configure git for private modules
        if: env.TOKEN != ''
        run: git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Generate vendor
        run: go mod vendor

  dockerize:
    runs-on: ["self-hosted", "${{ inputs.extra_label }}"]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.registry_user }}
          password: ${{ secrets.registry_pass }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: /opt/runner/data/dockerfiles/Dockerfile.${{ inputs.flavor }}
          push: true
          tags: ${{ inputs.registry_name }}/${{ github.event.repository.name }}:${{ github.sha }}