on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  config:
    uses: klever-io/test-sonarCloud/.github/workflows/go.yaml@master
    with:
      with_cache: true
    secrets:
      git_user: ${{ secrets.GIT_USER }}
      git_pass: ${{ secrets.GIT_PASS }}

  ci:
    uses: klever-io/test-sonarCloud/.github/workflows/go-ci.yaml@master
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
    needs: [config]